name: Test and build
on:
  push:
    paths:
      - src/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - src/**

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint

  build:
    name: Website build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Test site build
        run: yarn build

      - name: Commit changes if build has been successfull
        uses: EndBug/add-and-commit@v4
        with:
          add: dist
          message: "[auto] Commit dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
