name: Deploy
on:
  push:
    paths:
      - dist/**
      - .github/workflows/deploy.yml
    branches:
      - stable

jobs:
  deploy:
    name: Deploy to master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git config user.name "${GITHUB_ACTOR}"
      - run: git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: git fetch
      - run: git push origin `git subtree push --prefix dist origin master` --force
