name: Deploy
on:
  push:
    branches:
      - stable

jobs:
  deploy:
    name: Deploy to master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: git config user.name "${GITHUB_ACTOR}"
      - run: git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: npm run dist

      - run: git push origin `git subtree split --prefix dist stable`:master --force
